### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by alpriest** [TonyM1958/HA-FoxESS-Modbus#12]
Hi, I had this emailed me today:

> Thank you for supplying details for all the charted parameters. May I point out a couple of typos - see the attached screenshots.
> 
> Bat Current in amps (volts) ;
> Inv Temperature in degrees C (degress).
> 
> Richard (using wife's phone)

![Screenshot_20230807-201048-514](https://github.com/TonyM1958/HA-FoxESS-Modbus/assets/221241/bdddc555-3dd8-48de-b3c7-42fa6f8035e0)

![Screenshot_20230807-200944-651](https://github.com/TonyM1958/HA-FoxESS-Modbus/assets/221241/51b8208f-3680-4783-8d1b-9af6531a3a76)

**Comment by TonyM1958** [comment]
Ha ha. At least someone read it! Wish everything was so easily fixed.
