### ISSUE TITLE
Missing load_energy_total/load_energy_today

### ISSUE THREAD

**Issue by canton7** [TonyM1958/HA-FoxESS-Modbus#3]
load_energy_total: 11090-11091 and 32021-32022
load_energy_today: 11092 and 32023

Discovered from the H3 yaml file in stealthchesnut's repo

**Comment by TonyM1958** [comment]
Thanks - I've added these to the spread sheet. I'll do a scan later today and verify the values and also see if I can get someone to check their KH series inverter.

**Comment by canton7** [comment]
Cheers! If you have someone with a KH series, could you find out the serial (at 10000/30000 for 10 registers or so, decoded as ascii) please? Then I can add support to foxess_modbus.
